[package]
name = "akashic-project"
version = "0.1.0"
edition = "2021"

[lib]


[workspace]
members = [
    "akashic",
    "akashic-macro",
    "akashic-boot",
    "bevy-akashic",
    "bevy-akashic-patch"
]


[workspace.dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1.0.176", features = ["derive"] }
serde_json = "1.0.104"
js-sys = { version = "0.3.64" }
serde-wasm-bindgen = "0.6.0"
paste = "1.0.14"
auto-delegate = "0.0.9"
bevy = { version = "0.11.2", features = ["bevy_asset"] }
derive_builder = "0.12.0"
once_cell = "1.18.0"
anyhow = "1.0.75"
thiserror = "1.0.48"
bevy_mod_raycast = "0.13.1"

[dev-dependencies]
bevy = { version = "0.11", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_pbr",
    "bevy_sprite",
    "x11",
    "png"
] }
bevy_rapier2d = "0.22.0"
bevy-akashic = { path = "bevy-akashic", features = ["3d"] }
console_error_panic_hook = "0.1.7"
serde = { version = "1.0.167", features = ["derive"] }
env_logger = "0.10.0"

