[package]
name = "akashic-project"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "akashic-rs",
    "akashic-macro",
    "bevy-akashic",
    "akashic-boot"
]


[[example]]
name = "hello"
path = "examples/hello.rs"


[[example]]
name = "state"
path = "examples/state.rs"

[[example]]
name = "sample"
path = "examples/sample.rs"


[[example]]
name = "akashic_3d_with_default"
path = "examples/akashic_3d_with_default.rs"

[workspace.dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1.0.176", features = ["derive"] }
serde_json = "1.0.104"
js-sys = { version = "0.3.64" }
serde-wasm-bindgen = "0.6.0"
paste = "1.0.14"
auto-delegate = "0.0.9"
bevy = { version = "0.11", default-features = false, features = ["bevy_asset", "bevy_render", "bevy_core_pipeline", "bevy_gizmos", "bevy_scene", "bevy_sprite", "png"] }
derive_builder = "0.12.0"
once_cell = "1.18.0"
anyhow = "1.0.75"
thiserror = "1.0.48"


[dev-dependencies]
bevy = { version = "0.11", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_pbr",
    "bevy_sprite",
    "x11",
    "png"
] }
bevy_rapier2d = "0.22.0"
bevy-akashic = { path = "bevy-akashic", features = ["3d"] }
console_error_panic_hook = "0.1.7"
serde = { version = "1.0.167", features = ["derive"] }
env_logger = "0.10.0"