[package]
name = "bevy-akashic"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "akashic-rs",
    "akashic-macro",
    "bevy-akashic-engine",
]

[dependencies]
bevy = { workspace = true }
bevy-akashic-engine = { path = "./bevy-akashic-engine" }


[workspace.dependencies]
wasm-bindgen = { version = "0.2" }
serde = { version = "1.0.176", features = ["derive"] }
js-sys = "0.3.64"
serde-wasm-bindgen = "0.5.0"
paste = "1.0.14"
auto-delegate = "0.0.9"
bevy = "0.11.2"