[package]
name = "bevy-akashic"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "akashic-rs",
    "akashic-macro",
    "bevy-akashic-engine",
]

[dependencies]
bevy = { version = "0.11", default-features = false }
bevy-akashic-engine = { path = "./bevy-akashic-engine" }
console_error_panic_hook = "0.1.7"
serde = { workspace = true }
once_cell = { workspace = true }

[workspace.dependencies]
wasm-bindgen = { version = "0.2" , features = ["serde-serialize"] }
serde = { version = "1.0.176", features = ["derive"] }
serde_json = "1.0.104"
js-sys = {version = "0.3.64"}
serde-wasm-bindgen = "0.6.0"
paste = "1.0.14"
auto-delegate = "0.0.9"
bevy = { version = "0.11" }
derive_builder = "0.12.0"
once_cell = "1.18.0"
anyhow = "1.0.75"
thiserror = "1.0.48"