[package]
name = "bevy-akashic-patch"
version = "0.1.0"
edition = "2021"


[lib]


[dependencies]
bevy = { workspace = true }
bevy-akashic = { path = "../bevy-akashic" }
anyhow = { worksapce = true }
wasm-bindgen = { workspace = true }